name: Check Ignore Files

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  check-ignored-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for untracked ignored files
        run: |
          echo "Checking for untracked ignored files..."
          git ls-files --others --ignored --exclude-standard > .untracked-ignored.txt
          if [ -s .untracked-ignored.txt ]; then
            echo "Untracked but ignored files detected:"
            cat .untracked-ignored.txt
            exit 1
          else
            echo "No untracked ignored files found."
          fi

      - name: Check for tracked ignored files
        run: |
          echo "Checking for tracked ignored files..."
          git ls-files -i -c --exclude-standard > .tracked-ignored.txt
          if [ -s .tracked-ignored.txt ]; then
            echo "Tracked files that are listed in .gitignore detected:"
            cat .tracked-ignored.txt
            exit 1
          else
            echo "No tracked ignored files found."
          fi
