name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push server image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/last-stand-server:latest -f Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/last-stand-server:latest

      - name: Deploy to local server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.LOCAL_SERVER_HOST }}
          username: ${{ secrets.LOCAL_SERVER_USER }}
          key: ${{ secrets.LOCAL_SERVER_SSH_KEY }}
          script: |
            cd /home/your-user/last-stand-project
            docker-compose pull server
            docker-compose up -d --no-deps server
